### ISSUE TITLE
Bug [Minecraft 1.20.1, Aether: Redux 1.3.3]: Sentry Ring Gives You Double Jump When You Unequip, and Doesnt Work When Equipped

### ISSUE THREAD

**Issue by Bubby0304** [Zepalesque/The-Aether-Redux#37]
We are using Forge 42.2.0 and Minecraft 1.20.1, along side Aether: Redux 1.3.3.

The bug is exactly what the title suggests, the Sentry Ring, which is supposed to give you a double jump, doesnt work when equipped, but when unequipped you get infiinite double jump without a ring equipped.

To reproduce this bug, simply put a sentry ring on, and remove the sentry ring and see what happens.

To my understanding, this effect should only be present when the ring is put on. I have seen issues like this before with some of the added "trinkets" but this is the main one I know of at the top of my head.

Just so you know, this is occurring inside a modpack, but I do not think that is the issue as I remember this issue happening in the aether redux standalone as well.

**Comment by Zepalesque** [comment]
odd, I’ll look into it

**Comment by Zepalesque** [comment]
hmm, this seems to only happen on a server, I'll fix this for the next update

**Comment by Zepalesque** [comment]
fixed in v1.3.4
