### ISSUE TITLE
Bug [1.20.1]: Game Crashes on load with Optifine, Aether Redux, and Deep Aether installed

### ISSUE THREAD

**Issue by HierizenMatyr** [Zepalesque/The-Aether-Redux#39]
Forge Version: 47.2.16
Aether Redux Version: aether-redux-1.3.3-1.20.1-neoforge.jar

**Describe the bug**
When launching the game with Aether Redux mod installed alongside Optifine and Deep Aether the game will crash upon reaching
State Transition:  Load_Registries.

**To Reproduce**
Install Aether Redux, Deep Aether, Optifine and needed related dependencies 
Launch the game.
**Expected behavior**
Game to load properly without failure

**Screenshots**
<img width="807" alt="Crash" src="https://github.com/Zepalesque/Aether-Redux-Issue-Tracker/assets/153045365/f4d92115-5033-493c-8bc3-4cada2204918">

**Crash report (if necessary and/or applicable)**
[crash-2023-12-08_22.03.14-client.txt](https://github.com/Zepalesque/Aether-Redux-Issue-Tracker/files/13622942/crash-2023-12-08_22.03.14-client.txt)

**Log file (should be titled latest.log, if applicable)**
[latest.log](https://github.com/Zepalesque/Aether-Redux-Issue-Tracker/files/13622943/latest.log)

**Comment by Zepalesque** [comment]
unfortunately since optifine isn’t open-source, I can’t say _for sure_ whether or not I’ll be able to fix this, but I’ll look into it at some point

in the meantime, if you need performance mods I’ve been able to use both redux and deep aether together with embeddium, so that could also help

**Comment by HierizenMatyr** [comment]
Thank you for the response, I'll try out embeddium instead of Optifine or Rubidium.

**Comment by Zepalesque** [comment]
closing as at least I _assume_ embeddium worked
