### ISSUE TITLE
Bug [1.20.1]: Quicksoil doesn't work on servers

### ISSUE THREAD

**Issue by Buckeria** [Zepalesque/The-Aether-Redux#40]
Forge Version: 47.2.17 (both client and server)
Aether Redux Version: 1.3.3

**Describe the bug**
When playing on a server using the Aether Redux mod and its dependencies installed, quicksoil does not slide players, mobs, or items. This happens regardless of what setting is used for the quicksoil movement system in the config file.

**To Reproduce**
1. Setup a Forge server with the Aether Redux mod and its dependencies installed and start it.
2. Run a Forge client with the same mods installed and connect to the server.
3. Make your way to the Aether and find/place some quicksoil.
4. Walk around/drop an item/spawn a mob on the quicksoil.

**Expected behavior**
Quicksoil should slide players, mobs, and items around.

**Screenshots**
N/A

**Crash report (if necessary and/or applicable)**
N/A

**Log file (should be titled latest.log, if applicable)**
N/A

**Additional context**
The server host I was using when I discovered and recreated this bug was Pebblehost.

**Comment by Zepalesque** [comment]
Hmm, uh oh, that’s odd, I’ll look into it once I continue on the next update

**Comment by Zepalesque** [comment]
fixed in v1.3.4
