### ISSUE TITLE
Bug: [1.19.2] Customizable Elytra (customizableelytra) encountered an error during the common_setup event phase (Registry Object not present: aether:golden_parachute)

### ISSUE THREAD

**Issue by MoonMoonShark** [Zepalesque/The-Aether-Redux#41]
**What version of the mod, Forge/Neoforge and Minecraft are you using?**
**Specs:**
Minecraft 1.19.2
Forge 43.2.23

**Sample Modpack** (doesn't work when Redux enabled):
Customizable Elytra (customizableelytra-1.19.0-1.7.4)
Aeroblender (aeroblender-r1.19.2-1.0)
The Aether (aether-1.19.2-1.0.0-beta.2.2-forge)
The Aether: Redux (aether-redux-1.3.3-1.19.2-forge)
TerraBlender (TerraBlender-forge-1.19.2-2.0.1.166)

**Describe the bug**
seems to be a conflict with Customizable Elytra and The Aether: Redux. i've been trying to run them together in my modpack, but whenever i have them both, the game crashes on startup. i tried making a modpack with the bare minimum mods, and it crashes. when i remove either Redux or CE, it loads.

**To Reproduce**
1. start pack with both customizable elytra and aether: redux
2. game crashes
3. remove one or the other
4. game boots

**Expected behavior**

**Crash report (if necessary and/or applicable)**
https://pastebin.com/PcgBvsJW

**Additional context**
the crash log says it's Customizable Elytra that's crashing, but i ran it by their mod dev and they said it's on the Redux side, so i'm following up with you (https://github.com/Hidoni/CustomizableElytra/issues/35). hopefully between us all, we can figure it out. :)

please let me know if there is anything at all i can do to help! thank you for everything!

**Comment by Zepalesque** [comment]
hmm I'll look into it

**Comment by Zepalesque** [comment]
should be fixed in v1.3.4

**Comment by MoonMoonShark** [comment]
thank you! <3
